// <auto-generated />
namespace NinjaDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class interfaceColoumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(interfaceColoumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201709181715054_interfaceColoumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
